plugins {
    // Kotlin serialization plugin for type safe routes and navigation arguments
    id 'org.jetbrains.kotlin.plugin.serialization' version '2.0.21'
}
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-parcelize'
apply plugin: "kotlin-kapt"
apply plugin: 'dagger.hilt.android.plugin'
// Adding the apply plugin statement for safeargs
apply plugin: 'androidx.navigation.safeargs'

if (hasProperty('buildScan')) {
    buildScan {
        termsOfServiceUrl = 'https://gradle.com/terms-of-service'
        termsOfServiceAgree = 'yes'
    }
}

android {
    defaultConfig {
        minSdkVersion 21
        compileSdkVersion = 35
        targetSdk 35
        applicationId "de.teufelsturm.tt_downloader_ktx"
        versionCode 6
        versionName "0." + defaultConfig.versionCode.intdiv(10) + "." + defaultConfig.versionCode % 10
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled = true
    }

    // Enables data binding.
    buildFeatures {
        dataBinding true
        buildConfig true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            versionNameSuffix debugVersionNameSuffix
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_18
        targetCompatibility JavaVersion.VERSION_18
    }
    kotlinOptions {
        jvmTarget = '18'
    }
    namespace 'de.teufelsturm.tt_downloader_ktx'
}

// Allow references to generated code
kapt {
    correctErrorTypes = true
}

dependencies {
    def nav_version = "2.8.4"
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    // Support libraries
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.fragment:fragment-ktx:1.8.5'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.0'
    // Android KTX
    implementation 'androidx.core:core-ktx:1.15.0'
    // Room and Lifecycle dependencies
    implementation "androidx.room:room-runtime:$room_version"
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.test.ext:junit-ktx:1.2.1'
    kapt "androidx.room:room-compiler:$room_version"
    implementation "androidx.lifecycle:lifecycle-extensions:2.2.0"
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.7'
    // Kotlin Extensions and Coroutines support for Room
    implementation "androidx.room:room-ktx:$room_version"
    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    // Coroutines
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutine_version"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$coroutine_version"
    // Navigation
    // Jetpack Compose Integration
    implementation "androidx.navigation:navigation-compose:$nav_version"

    // Views/Fragments Integration
    implementation "androidx.navigation:navigation-fragment:$nav_version"
    implementation "androidx.navigation:navigation-ui:$nav_version"

    // Feature module support for Fragments
    implementation "androidx.navigation:navigation-dynamic-features-fragment:$nav_version"

    // Testing Navigation
    androidTestImplementation "androidx.navigation:navigation-testing:$nav_version"

    // JSON serialization library, works with the Kotlin serialization plugin.
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3"
    // Material Design
    implementation 'com.google.android.material:material:1.12.0'
    // CardView
    implementation "androidx.cardview:cardview:1.0.0"

    //Dagger - Hilt
    implementation("com.google.dagger:hilt-android:$hilt_version")
    kapt("com.google.dagger:hilt-android-compiler:$hilt_version")

    // Activity KTX for viewModels()
    implementation 'androidx.activity:activity-ktx:1.9.3'

    // multiDexEnabled
    implementation 'com.android.support:multidex:1.0.3'

    /// ADDITIONAL / EXTERNAL LIBRARIES
    // Image Loader from external source
    implementation('io.coil-kt:coil:2.7.0')
    // TouchImageView
    implementation 'com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0'


    // Testing
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    androidTestImplementation "android.arch.core:core-testing:1.1.1"
    androidTestImplementation 'com.google.truth:truth:1.4.4'
    testImplementation 'androidx.arch.core:core-testing:2.2.0'
    testImplementation 'com.google.truth:truth:1.4.4'
    testImplementation 'com.nhaarman:mockito-kotlin:1.6.0'
    testImplementation 'org.mockito:mockito-inline:5.2.0'
}